compressionLevel: mixed

defaultSemverRangePrefix: ""

enableColors: true

enableGlobalCache: true

enableImmutableInstalls: false

nodeLinker: node-modules

npmMinimalAgeGate: 7d

yarnPath: .yarn/releases/yarn-4.14.1.cjs
