name: Release (Beta)
on:
  push:
    branches:
      - beta
jobs:
  release-beta:
    name: Release Beta
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Check for existing release PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          existing_pr=$(gh pr list --state open --json title --jq '.[] | select(.title | contains("Version Packages (beta)"))')
          if [ -n "$existing_pr" ]; then
            echo "Beta Release PR already exists."
            echo "SKIP_RELEASE=true" >> $GITHUB_ENV
          fi

      - name: Install Dependencies
        if: ${{ env.SKIP_RELEASE != 'true' }}
        run: yarn install

      - name: Build
        if: ${{ env.SKIP_RELEASE != 'true' }}
        run: yarn build

      - name: Authenticate with npm
        if: ${{ env.SKIP_RELEASE != 'true' }}
        run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}

      - name: Create Beta Release
        if: ${{ env.SKIP_RELEASE != 'true' }}
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn changeset version
          publish: yarn changeset:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
